[package]
name = "s1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web ={ workspace=true }
tokio = {workspace=true}
num_cpus = {workspace=true}
openssl = {workspace=true}